version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: inventory-sql
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=YourPassword123!
    ports:
      - "1433:1433"
    restart: always
